baseURL = 'https://codecircuits.com/'
languageCode = 'en-us'
title = "Code Circuits"
theme = 'github.com/mansoorbarri/Roadster'

[author]
email = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'